controller_list:
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - RSP
      - RSR
      - RSY
      - REP
      - RWY
      - RWP
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - LSP
      - LSR
      - LSY
      - LEP
      - LWY
      - LWP
  - name: left_leg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - LHY
      - LHR
      - LHP
      - LKP
      - LAP
      - LAR
  - name: right_leg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - RHY
      - RHR
      - RHP
      - RKP
      - RAP
      - RAR
