controller_list:
  - name: huboplus/left_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [LSP, LSR, LSY, LEP, LWY, LWP]
  - name: huboplus/right_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [RSP, RSR, RSY, REP, RWY, RWP]
  - name: huboplus/legs_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [LHY, LHR, LHP, LKP, LAP, LAR,
             RHY, RHR, RHP, RKP, RAP, RAR]
